---
- name: Pull nexus image
  docker_image:
    name: sonatype/nexus3
    source: pull

- name: Run nexus container
  command: docker run -dit -p 8081:8081 --restart=always --name nexus sonatype/nexus3
  ignore_errors: yes

- name: Tag image and push it to private registry
  docker_image:
    name: sonatype/nexus3
    repository: localhost:5000/sonatype/nexus3
    push: yes
    source: local

- name: Wait for Nexus to start up before proceeding.
  command: >
    curl -D - --silent --max-time 5 http://localhost:8081/
  args:
    warn: false
  register: result
  until: >
    (result.stdout.find("403 Forbidden") != -1)
    or (result.stdout.find("200 OK") != -1)
  retries: "60"
  delay: "5"
  changed_when: false
  check_mode: false

- name: Get nexus admin initial password
  command: docker exec -it nexus cat /nexus-data/admin.password
  register: nexuspass

- name: Print nexus admin initial password
  debug:
    msg: "{{ nexuspass.stdout }}"
