- name: Install Epel-Release
  yum: 
    name: epel-release
    state: latest

- name: Install Python-Pip
  yum: 
    name: python-pip
    state: latest
  
- name: Install Docker-Py
  command: pip install python-jenkins